---
title: "Network_change_eleginoides"
output: html_document
---

First run all matrix in network_exps.rmd

Make matrix and get change

```{r}
library(igraph)
```


```{r}
#E_Base
E_Base <- matrix_Base_ordered
E_Base[,c(1:16)] <- 0
E_Base[,18] <- 0

# play_E_Base <- E_Base[,-c(1:16)]
# play_E_Base <- play_E_Base[,-2]
# play_E_Base <- as.data.frame(play_E_Base)

#E_KI
E_KI <- matrix_KI_ordered
E_KI[,c(1:16)] <- 0
E_KI[,18] <- 0

# play_E_KI <- E_KI[,-c(1:16)]
# play_E_KI <- play_E_KI[,-2]
# play_E_KI <- as.data.frame(play_E_KI)

# play_Base_KI_E <- cbind(play_E_Base, play_E_KI)
# fwrite(play_Base_KI_E, "Base_KI_E.csv", row.names = T)
Base_KI_Diff_E <- read.csv("Base_KI_E_edited.csv")

#E_KD
E_KD <- matrix_KD_ordered
E_KD[,c(1:16)] <- 0
E_KD[,18] <- 0

# play_E_KD <- E_KD[,-c(1:16)]
# play_E_KD <- play_E_KD[,-2]
# play_E_KD <- as.data.frame(play_E_KD)

# play_Base_KD_E <- cbind(play_E_Base, play_E_KD)
# fwrite(play_Base_KD_E, "Base_KD_E.csv", row.names = T)
Base_KD_Diff_E <- read.csv("Base_KD_E_edited.csv")

#E_LI
E_LI <- matrix_LI_ordered
E_LI[,c(1:16)] <- 0
E_LI[,18] <- 0

# play_E_LI <- E_LI[,-c(1:16)]
# play_E_LI <- play_E_LI[,-2]
# play_E_LI <- as.data.frame(play_E_LI)
# 
# play_Base_LI_E <- cbind(play_E_Base, play_E_LI)
# fwrite(play_Base_LI_E, "Base_LI_E.csv", row.names = T)
Base_LI_Diff_E <- read.csv("Base_LI_E_edited.csv")

#E_LD
E_LD <- matrix_LD_ordered
E_LD[,c(1:16)] <- 0
E_LD[,18] <- 0

# play_E_LD <- E_LD[,-c(1:16)]
# play_E_LD <- play_E_LD[,-2]
# play_E_LD <- as.data.frame(play_E_LD)
# 
# play_Base_LD_E <- cbind(play_E_Base, play_E_LD)
# fwrite(play_Base_LD_E, "Base_LD_E.csv", row.names = T)
Base_LD_Diff_E <- read.csv("Base_LD_E_edited.csv")

#E_KILI
E_KILI <- matrix_KILI_ordered
E_KILI[,c(1:16)] <- 0
E_KILI[,18] <- 0

# play_E_KILI <- E_KILI[,-c(1:16)]
# play_E_KILI <- play_E_KILI[,-2]
# play_E_KILI <- as.data.frame(play_E_KILI)
# 
# play_Base_KILI_E <- cbind(play_E_Base, play_E_KILI)
# fwrite(play_Base_KILI_E, "Base_KILI_E.csv", row.names = T)
Base_KILI_Diff_E <- read.csv("Base_KILI_E_edited.csv")

#E_KDLD
E_KDLD <- matrix_KDLD_ordered
E_KDLD[,c(1:16)] <- 0
E_KDLD[,18] <- 0

# play_E_KDLD <- E_KDLD[,-c(1:16)]
# play_E_KDLD <- play_E_KDLD[,-2]
# play_E_KDLD <- as.data.frame(play_E_KDLD)
# 
# play_Base_KDLD_E <- cbind(play_E_Base, play_E_KDLD)
# fwrite(play_Base_KDLD_E, "Base_KDLD_E.csv", row.names = T)
Base_KDLD_Diff_E <- read.csv("Base_KDLD_E_edited.csv")

#E_KILD
E_KILD <- matrix_KILD_ordered
E_KILD[,c(1:16)] <- 0
E_KILD[,18] <- 0

# play_E_KILD <- E_KILD[,-c(1:16)]
# play_E_KILD <- play_E_KILD[,-2]
# play_E_KILD <- as.data.frame(play_E_KILD)
# 
# play_Base_KILD_E <- cbind(play_E_Base, play_E_KILD)
# fwrite(play_Base_KILD_E, "Base_KILD_E.csv", row.names = T)
Base_KILD_Diff_E <- read.csv("Base_KILD_E_edited.csv")

#E_KDLI
E_KDLI <- matrix_KDLI_ordered
E_KDLI[,c(1:16)] <- 0
E_KDLI[,18] <- 0

# play_E_KDLI <- E_KDLI[,-c(1:16)]
# play_E_KDLI <- play_E_KDLI[,-2]
# play_E_KDLI <- as.data.frame(play_E_KDLI)
# 
# play_Base_KDLI_E <- cbind(play_E_Base, play_E_KDLI)
# fwrite(play_Base_KDLI_E, "Base_KDLI_E.csv", row.names = T)
Base_KDLI_Diff_E <- read.csv("Base_KDLI_E_edited.csv")


```


Now make the plots!

```{r}
legend_label <- c("1. Resource", "2. P.bolini", "3. K.anderssoni", "4. C.microdon", "5. G.fraseri", "6. E.carlsbergi", "7. G.braueri", "8. E.antarctica", "9. B.antarcticus", "10. N.achirus", "11. G.nicholsi", "12. P.antarcticum", "13. N.coatsi", "14. C. piriei", "15. P.gracilis", "16. C.gunnari", "17. D.eleginoides", "18. D.mawsoni" )

#E_Base diff

network_E_Base <- graph_from_adjacency_matrix(E_Base, weighted= TRUE, mode= "directed")
V(network_E_Base)$size <- 10
E(network_E_Base)$width <- E(network_E_Base)$weight/3000
V(network_E_Base)$color <- "Black"
vertex_attr(network_E_Base)
V(network_E_Base)$label <- c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18)
plot(network_E_Base, layout= layout.circle, vertex.label.color="white", vertex.label.cex=0.7, vertex.label.font= 2,
     edge.color="slategray",
     # main= "Biomass flow D.eleginoides- Base",
     edge.arrow.size = 0.001, vertex.label.family="Helvetica", vertex.label.dist= 0, vertex.label.degree= pi/2, edge.curved=.1)
# legend(x= -1.5, y= 0.7, legend_label, col = "black", cex = 0.6, bty = "n", ncol=1)

#E_KI diff

network_E_KI <- graph_from_adjacency_matrix(E_KI, weighted= TRUE, mode= "directed")
V(network_E_KI)$size <- 10
E(network_E_KI)$width <- E(network_E_KI)$weight/3000
V(network_E_KI)$color <- "black"

cols <- c("purple", "orange","orange","orange","orange","orange","orange","orange","orange","orange","orange","orange","orange","orange","orange","orange","orange","orange")

E(network_E_KI)$color <- cols
V(network_E_KI)$label <- c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18)
plot(network_E_KI, layout= layout.circle, vertex.label.color="white",vertex.label.cex=0.7,
     main= "Biomass flow D.eleginoides- KI",
     edge.arrow.size = 0.1, vertex.label.family="Helvetica", vertex.label.dist= 0, vertex.label.degree= pi/2, edge.curved=.1)


#E_KD diff

network_E_KD <- graph_from_adjacency_matrix(E_KD, weighted= TRUE, mode= "directed")
V(network_E_KD)$size <- 10
E(network_E_KD)$width <- E(network_E_KD)$weight/3000
V(network_E_KD)$color <- "black"
vertex_attr(network_E_KD)
V(network_E_KD)$label <- c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18)

cols <- c("orange", "purple","orange", "purple", "purple", "purple","purple","purple","purple","purple","purple","purple","purple","purple","purple","purple","purple","purple")

E(network_E_KD)$color <- cols
plot(network_E_KD, layout= layout.circle, vertex.label.color="white",vertex.label.cex=0.6,
     main= "Biomass flow D.eleginoides- KD", 
     edge.arrow.size = 0.1, vertex.label.family="Helvetica", vertex.label.dist= 0, vertex.label.degree= pi/2, edge.curved=.1)


#E_LI DIFF

network_E_LI <- graph_from_adjacency_matrix(E_LI, weighted= TRUE, mode= "directed")
V(network_E_LI)$size <- 10
E(network_E_LI)$width <- E(network_E_LI)$weight/3000
V(network_E_LI)$color <- "black"

cols <- c("orange","purple", "purple", "purple", "purple","purple","purple","purple","purple","purple","purple","purple","purple","purple","purple","purple","purple", "purple")

E(network_E_LI)$color <- cols
V(network_E_LI)$label <- c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18)
plot(network_E_LI, layout= layout.circle, vertex.label.color="white",vertex.label.cex=0.6,
     main= "Biomass flow D.eleginoides- LI",
     edge.arrow.size = 0.1, vertex.label.family="Helvetica", vertex.label.dist= 0, vertex.label.degree= pi/2, edge.curved=.1)

#E_LD diff

network_E_LD <- graph_from_adjacency_matrix(E_LD, weighted= TRUE, mode= "directed")
V(network_E_LD)$size <- 10
E(network_E_LD)$width <- E(network_E_LD)$weight/3000
V(network_E_LD)$color <- "black"

cols <- c("purple", "orange","orange","orange","orange","orange","orange","orange","orange","orange","orange","orange","orange","orange","orange","orange","orange","orange")

E(network_E_LD)$color <- cols
V(network_E_LD)$label <- c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18)
plot(network_E_LD, layout= layout.circle, vertex.label.color="white",vertex.label.cex=0.6,
     main= "Biomass flow D.eleginoides- LD",
     edge.arrow.size = 0.1, vertex.label.family="Helvetica", vertex.label.dist= 0, vertex.label.degree= pi/2, edge.curved=.1)

#E_KILI_DIFF

network_E_KILI <- graph_from_adjacency_matrix(E_KILI, weighted= TRUE, mode= "directed")
V(network_E_KILI)$size <- 10
E(network_E_KILI)$width <- E(network_E_KILI)$weight/3000

cols <- c("purple","purple","purple","purple","purple","purple","purple","purple","purple","orange","purple","orange","orange","orange","orange","orange","orange","orange")

E(network_E_KILI)$color <- cols
V(network_E_KILI)$label <- c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18)
V(network_E_KILI)$color <- "black"
plot(network_E_KILI, layout= layout.circle, vertex.label.color="white",vertex.label.cex=0.6,
     main= "Biomass flow D.eleginoides- KI_LI",
     edge.arrow.size = 0.1, vertex.label.family="Helvetica", vertex.label.dist= 0, vertex.label.degree= pi/2, edge.curved=.1)

#E_KDLD_DIFF

network_E_KDLD <- graph_from_adjacency_matrix(E_KDLD, weighted= TRUE, mode= "directed")
V(network_E_KDLD)$size <- 10
E(network_E_KDLD)$width <- E(network_E_KDLD)$weight/3000
V(network_E_KDLD)$color <- "black"

cols <- c("orange","orange","orange","orange","orange","orange","orange","orange","orange","purple","orange","purple","purple","purple","purple","purple","purple","purple")
          
E(network_E_KDLD)$color <- cols
V(network_E_KDLD)$label <- c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18)
plot(network_E_KDLD, layout= layout.circle, vertex.label.color="white",vertex.label.cex=0.6,
     main= "Biomass flow D.eleginoides- KD_LD",
     edge.arrow.size = 0.1, vertex.label.family="Helvetica", vertex.label.dist= 0, vertex.label.degree= pi/2, edge.curved=.1)

#E_KILD_DIFF

network_E_KILD <- graph_from_adjacency_matrix(E_KILD, weighted= TRUE, mode= "directed")
V(network_E_KILD)$size <- 10
E(network_E_KILD)$width <- E(network_E_KILD)$weight/3000
V(network_E_KILD)$color <- "black"

cols <- c("purple", "orange","orange","orange","orange","orange","orange","orange","orange","orange","orange","orange","orange","orange","orange","orange","orange","orange")

E(network_E_KILD)$color <- cols
V(network_E_KILD)$label <- c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18)
plot(network_E_KILD, layout= layout.circle, vertex.label.color="white",vertex.label.cex=0.6,
     main= "Biomass flow D.eleginoides KILD",
     edge.arrow.size = 0.1, vertex.label.family="Helvetica", vertex.label.dist= 0, vertex.label.degree= pi/2, edge.curved=.1)

#E_KDLI_DIFF

network_E_KDLI <- graph_from_adjacency_matrix(E_KDLI, weighted= TRUE, mode= "directed")
V(network_E_KDLI)$size <- 10
E(network_E_KDLI)$width <- E(network_E_KDLI)$weight/3000
V(network_E_KDLI)$color <- "black"

cols <- c("orange","purple", "purple", "purple", "purple","purple","purple","purple","purple","purple","purple","purple","purple","purple","purple","purple","purple", "purple")

E(network_E_KDLI)$color <- cols
V(network_E_KDLI)$label <- c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18)
plot(network_E_KDLI, layout= layout.circle, vertex.label.color="white",vertex.label.cex=0.6,
     main= "Biomass flow D.eleginoides KDLI",
     edge.arrow.size = 0.1, vertex.label.family="Helvetica", vertex.label.dist= 0, vertex.label.degree= pi/2, edge.curved=.1)

```


