---
title: "Network_change_Mawsoni"
output: html_document
---
First run all matrix scripts in Network_exps.Rmd

Plot base, KI_LI and KD_LD for D.mawsoni
```{r}
library(igraph)

#M_Base
M_Base <- matrix_Base_ordered
M_Base[,c(1:17)] <- 0

# library(igraph)
network_M_Base <- graph_from_adjacency_matrix(M_Base, weighted= TRUE, mode= "directed")
V(network_M_Base)$size <- log(SOparams_r$w_inf)*3
E(network_M_Base)$width <- E(network_M_Base)$weight/2000
colfunc <- colorRampPalette(c("gray80", "darkred"))
cols<-colfunc(18)
V(network_M_Base)$color <- cols
vertex_attr(network_M_Base)
V(network_M_Base)$label <- c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18)
#to change the edge colours: can do by colouring from the source 
edge.start <- ends(network_M_Base, es=E(network_M_Base), names=F)[,1]
edge.col <- V(network_M_Base)$color[edge.start]
plot(network_M_Base, layout= layout.circle, vertex.label.color="black",vertex.label.cex=0.6,
     main= "Biomass flow D.Mawsoni- Base", edge.color=edge.col,
     edge.arrow.size = 0.1, vertex.label.family="Helvetica", vertex.label.dist= 0, vertex.label.degree= pi/2, edge.curved=.1)
legend(x=1.5, y= 0.4, c(V(network_M_Base)$name), col = cols, pch = 18, pt.bg = V(network_M_Base)$label, pt.cex =0.5, cex = 0.6, bty = "n", ncol=2)

#M_KI

M_KI <- matrix_KI_ordered
M_KI[,c(1:17)] <- 0

network_M_KI <- graph_from_adjacency_matrix(M_KI, weighted= TRUE, mode= "directed")
V(network_M_KI)$size <- log(SOparams_r$w_inf)*3
E(network_M_KI)$width <- E(network_M_KI)$weight/2000
colfunc <- colorRampPalette(c("gray80", "darkred"))
cols<-colfunc(18)
V(network_M_KI)$color <- cols
vertex_attr(network_M_KI)
V(network_M_KI)$label <- c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18)
#to change the edge colours: can do by colouring from the source 
edge.start <- ends(network_M_KI, es=E(network_M_KI), names=F)[,1]
edge.col <- V(network_M_KI)$color[edge.start]
plot(network_M_KI, layout= layout.circle, vertex.label.color="black",vertex.label.cex=0.6,
     main= "Biomass flow D.Mawsoni- KI", edge.color=edge.col,
     edge.arrow.size = 0.1, vertex.label.family="Helvetica", vertex.label.dist= 0, vertex.label.degree= pi/2, edge.curved=.1)
legend(x=1.5, y= 0.4, c(V(network_M_KI)$name), col = cols, pch = 18, pt.bg = V(network_M_KI)$label, pt.cex =0.5, cex = 0.6, bty = "n", ncol=2)

#M_KD

M_KD <- matrix_KD_ordered
M_KD[,c(1:17)] <- 0

network_M_KD <- graph_from_adjacency_matrix(M_KD, weighted= TRUE, mode= "directed")
V(network_M_KD)$size <- log(SOparams_r$w_inf)*3
E(network_M_KD)$width <- E(network_M_KD)$weight/2000
colfunc <- colorRampPalette(c("gray80", "darkred"))
cols<-colfunc(18)
V(network_M_KD )$color <- cols
vertex_attr(network_M_KD)
V(network_M_KD)$label <- c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18)
#to change the edge colours: can do by colouring from the source 
edge.start <- ends(network_M_KD, es=E(network_M_KD), names=F)[,1]
edge.col <- V(network_M_KD)$color[edge.start]
plot(network_M_KD, layout= layout.circle, vertex.label.color="black",vertex.label.cex=0.6,
     main= "Biomass flow D.Mawsoni- KD", edge.color=edge.col,
     edge.arrow.size = 0.1, vertex.label.family="Helvetica", vertex.label.dist= 0, vertex.label.degree= pi/2, edge.curved=.1)
legend(x=1.5, y= 0.4, c(V(network_M_KD)$name), col = cols, pch = 18, pt.bg = V(network_M_KD)$label, pt.cex =0.5, cex = 0.6, bty = "n", ncol=2)

#M_LI

M_LI <- matrix_LI_ordered
M_LI[,c(1:17)] <- 0

network_M_LI <- graph_from_adjacency_matrix(M_LI, weighted= TRUE, mode= "directed")
V(network_M_LI)$size <- log(SOparams_r$w_inf)*3
E(network_M_LI)$width <- E(network_M_LI)$weight/2000
colfunc <- colorRampPalette(c("gray80", "darkred"))
cols<-colfunc(18)
V(network_M_LI)$color <- cols
vertex_attr(network_M_LI)
V(network_M_LI)$label <- c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18)
#to change the edge colours: can do by colouring from the source 
edge.start <- ends(network_M_LI, es=E(network_M_LI), names=F)[,1]
edge.col <- V(network_M_LI)$color[edge.start]
plot(network_M_LI, layout= layout.circle, vertex.label.color="black",vertex.label.cex=0.6,
     main= "Biomass flow D.Mawsoni- LI", edge.color=edge.col,
     edge.arrow.size = 0.1, vertex.label.family="Helvetica", vertex.label.dist= 0, vertex.label.degree= pi/2, edge.curved=.1)
legend(x=1.5, y= 0.4, c(V(network_M_LI)$name), col = cols, pch = 18, pt.bg = V(network_M_LI)$label, pt.cex =0.5, cex = 0.6, bty = "n", ncol=2)


#M_LD

M_LD <- matrix_LD_ordered
M_LD[,c(1:17)] <- 0

network_M_LD <- graph_from_adjacency_matrix(M_LD, weighted= TRUE, mode= "directed")
V(network_M_LD)$size <- log(SOparams_r$w_inf)*3
E(network_M_LD)$width <- E(network_M_LD)$weight/2000
colfunc <- colorRampPalette(c("gray80", "darkred"))
cols<-colfunc(18)
V(network_M_LD )$color <- cols
vertex_attr(network_M_LD)
V(network_M_LD)$label <- c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18)
#to change the edge colours: can do by colouring from the source 
edge.start <- ends(network_M_LD, es=E(network_M_LD), names=F)[,1]
edge.col <- V(network_M_LD)$color[edge.start]
plot(network_M_LD, layout= layout.circle, vertex.label.color="black",vertex.label.cex=0.6,
     main= "Biomass flow D.Mawsoni- LD", edge.color=edge.col,
     edge.arrow.size = 0.1, vertex.label.family="Helvetica", vertex.label.dist= 0, vertex.label.degree= pi/2, edge.curved=.1)
legend(x=1.5, y= 0.4, c(V(network_M_LD)$name), col = cols, pch = 18, pt.bg = V(network_M_LD)$label, pt.cex =0.5, cex = 0.6, bty = "n", ncol=2)

#M_KILI
M_KILI <- matrix_KILI_ordered
M_KILI[,c(1:17)] <- 0

network_M_KILI <- graph_from_adjacency_matrix(M_KILI, weighted= TRUE, mode= "directed")
V(network_M_KILI)$size <- log(SOparams_r$w_inf)*3
E(network_M_KILI)$width <- E(network_M_KILI)$weight/2000
colfunc <- colorRampPalette(c("gray80", "darkred"))
cols<-colfunc(18)
V(network_M_KILI)$color <- cols
vertex_attr(network_M_KILI)
V(network_M_KILI)$label <- c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18)
#to change the edge colours: can do by colouring from the source 
edge.start <- ends(network_M_KILI, es=E(network_M_KILI), names=F)[,1]
edge.col <- V(network_M_KILI)$color[edge.start]
plot(network_M_KILI, layout= layout.circle, vertex.label.color="black",vertex.label.cex=0.6,
     main= "Biomass flow D.Mawsoni- KI_LI", edge.color=edge.col,
     edge.arrow.size = 0.1, vertex.label.family="Helvetica", vertex.label.dist= 0, vertex.label.degree= pi/2, edge.curved=.1)
legend(x=1.5, y= 0.4, c(V(network_M_KILI)$name), col = cols, pch = 18, pt.bg = V(network_M_KILI)$label, pt.cex =0.5, cex = 0.6, bty = "n", ncol=2)


#M_KDLD
M_KDLD <- matrix_KDLD_ordered
M_KDLD[,c(1:17)] <- 0

network_M_KDLD <- graph_from_adjacency_matrix(M_KDLD, weighted= TRUE, mode= "directed")
V(network_M_KDLD)$size <- log(SOparams_r$w_inf)*3
E(network_M_KDLD)$width <- E(network_M_KDLD)$weight/2000
colfunc <- colorRampPalette(c("gray80", "darkred"))
cols<-colfunc(18)
V(network_M_KDLD)$color <- cols
vertex_attr(network_M_KDLD)
V(network_M_KDLD)$label <- c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18)
#to change the edge colours: can do by colouring from the source 
edge.start <- ends(network_M_KDLD, es=E(network_M_KDLD), names=F)[,1]
edge.col <- V(network_M_KDLD)$color[edge.start]
plot(network_M_KDLD, layout= layout.circle, vertex.label.color="black",vertex.label.cex=0.6,
     main= "Biomass flow D.Mawsoni- KD_LD", edge.color=edge.col,
     edge.arrow.size = 0.1, vertex.label.family="Helvetica", vertex.label.dist= 0, vertex.label.degree= pi/2, edge.curved=.1)
legend(x=1.5, y= 0.4, c(V(network_M_KILI)$name), col = cols, pch = 18, pt.bg = V(network_M_KILI)$label, pt.cex =0.5, cex = 0.6, bty = "n", ncol=2)

#matrix_KILD

M_KILD <- matrix_KILD_ordered
M_KILD[,c(1:17)] <- 0

network_M_KILD <- graph_from_adjacency_matrix(M_KILD, weighted= TRUE, mode= "directed")
V(network_M_KILD)$size <- log(SOparams_r$w_inf)*3
E(network_M_KILD)$width <- E(network_M_KILD)$weight/2000
colfunc <- colorRampPalette(c("gray80", "darkred"))
cols<-colfunc(18)
V(network_M_KILD)$color <- cols
vertex_attr(network_M_KILD)
V(network_M_KILD)$label <- c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18)
#to change the edge colours: can do by colouring from the source 
edge.start <- ends(network_M_KILD, es=E(network_M_KILD), names=F)[,1]
edge.col <- V(network_M_KILD)$color[edge.start]
plot(network_M_KILD, layout= layout.circle, vertex.label.color="black",vertex.label.cex=0.6,
     main= "Biomass flow D.mawsoni KILD", edge.color=edge.col,
     edge.arrow.size = 0.1, vertex.label.family="Helvetica", vertex.label.dist= 0, vertex.label.degree= pi/2, edge.curved=.1)
legend(x=1.5, y= 0.4, c(V(network_M_KILD)$name), col = cols, pch = 18, pt.bg = V(network_M_KILD)$label, pt.cex =0.5, cex = 0.6, bty = "n", ncol=2)

#matrix_KDLI

M_KDLI <- matrix_KDLI_ordered
M_KDLI[,c(1:17)] <- 0

network_M_KDLI <- graph_from_adjacency_matrix(M_KDLI, weighted= TRUE, mode= "directed")
V(network_M_KDLI)$size <- log(SOparams_r$w_inf)*3
E(network_M_KDLI)$width <- E(network_M_KDLI)$weight/2000
colfunc <- colorRampPalette(c("gray80", "darkred"))
cols<-colfunc(18)
V(network_M_KDLI)$color <- cols
vertex_attr(network_M_KDLI)
V(network_M_KDLI)$label <- c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18)
#to change the edge colours: can do by colouring from the source 
edge.start <- ends(network_M_KDLI, es=E(network_M_KDLI), names=F)[,1]
edge.col <- V(network_M_KDLI)$color[edge.start]
plot(network_M_KDLI, layout= layout.circle, vertex.label.color="black",vertex.label.cex=0.6,
     main= "Biomass flow D.mawsoni KDLI", edge.color=edge.col,
     edge.arrow.size = 0.1, vertex.label.family="Helvetica", vertex.label.dist= 0, vertex.label.degree= pi/2, edge.curved=.1)
legend(x=1.5, y= 0.4, c(V(network_M_KDLI)$name), col = cols, pch = 18, pt.bg = V(network_M_KDLI)$label, pt.cex =0.5, cex = 0.6, bty = "n", ncol=2)

```

Ok now want to change edge colour depending on whether the value increases or decreases. 

Data wrangling first
```{r}
#first put the three columns from each scenario into a data frame to look at change
# play_M_Base <- M_Base[,-c(1:17)]
# play_M_Base <- as.data.frame(play_M_Base)
# 
# play_M_KI <- M_KI[,-c(1:17)]
# play_M_KI <- as.data.frame(play_M_KI)
# 
# play_M_KD <- M_KD[,-c(1:17)]
# play_M_KD <- as.data.frame(play_M_KD)
# 
# play_M_LI <- M_LI[,-c(1:17)]
# play_M_LI <- as.data.frame(play_M_LI)
# 
# play_M_LD <- M_LD[,-c(1:17)]
# play_M_LD <- as.data.frame(play_M_LD)
# 
# play_M_KILI <- M_KILI[,-c(1:17)]
# play_M_KILI <- as.data.frame(play_M_KILI)
# 
# play_M_KDLD <- M_KDLD[,-c(1:17)]
# play_M_KDLD <- as.data.frame(play_M_KDLD)
# 
# play_M_KILD <- M_KILD[,-c(1:17)]
# play_M_KILD <- as.data.frame(play_M_KILD)
# 
# play_M_KDLI <- M_KDLI[,-c(1:17)]
# play_M_KDLI <- as.data.frame(play_M_KDLI)

#getting difference
# play_combined <- cbind(play_M_Base, play_M_KILI, play_M_KDLD)

# play_Base_KI <- cbind(play_M_Base, play_M_KI)
# fwrite(play_Base_KI, "Base_KI.csv", row.names = T)
Base_KI_Diff <- read.csv("Base_KI_Edited.csv")

# play_Base_KD <- cbind(play_M_Base, play_M_KD)
# fwrite(play_Base_KD, "Base_KD.csv", row.names = T)
Base_KD_Diff <- read.csv("Base_KD_edited.csv")

# play_Base_LI <- cbind(play_M_Base, play_M_LI)
# fwrite(play_Base_LI, "Base_LI.csv", row.names = T)
Base_LI_Diff <- read.csv("Base_LI_edited.csv")

# play_Base_LD <- cbind(play_M_Base, play_M_LD)
# fwrite(play_Base_LD, "Base_LD.csv", row.names = T)
Base_LD_Diff <- read.csv("Base_LD_edited.csv")

# play_Base_KILI <- cbind(play_M_Base, play_M_KILI)
# fwrite(play_Base_KILI, "Base_KILI.csv", row.names = T)
Base_KILI_Diff <- read.csv("Base_KILI_edited.csv")

# play_Base_KDLD <- cbind(play_M_Base, play_M_KDLD)
# fwrite(play_Base_KDLD, "Base_KDLD.csv", row.names = T)
Base_KDLD_Diff <- read.csv("Base_KDLD_edited.csv")

# play_Base_KILD <- cbind(play_M_Base, play_M_KILD)
# fwrite(play_Base_KILD, "Base_KILD.csv", row.names = T)
Base_KILD_Diff <- read.csv("Base_KILD_edited.csv")

# play_Base_KDLI <- cbind(play_M_Base, play_M_KDLI)
# fwrite(play_Base_KDLI, "Base_KDLI.csv", row.names = T)
Base_KDLI_Diff <- read.csv("Base_KDLI_edited.csv")


```


Ok we now have our differences. Now want to change colour of plots to represent + or - change
```{r}
# library(binovisualfields)
# library(igraph)
#keep same graph values, just change colours

legend_label <- c("1. Resource", "2. P.bolini", "3. K.anderssoni", "4. C.microdon", "5. G.fraseri", "6. E.carlsbergi", "7. G.braueri", "8. E.antarctica", "9. B.antarcticus", "10. N.achirus", "11. G.nicholsi", "12. P.antarcticum", "13. N.coatsi", "14. C. piriei", "15. P.gracilis", "16. C.gunnari", "17. D.eleginoides", "18. D.mawsoni" )

#M_Base diff
M_Base <- matrix_Base_ordered
M_Base[,c(1:17)] <- 0
network_M_Base <- graph_from_adjacency_matrix(M_Base, weighted= TRUE, mode= "directed")
V(network_M_Base)$size <- 10
E(network_M_Base)$width <- E(network_M_Base)$weight/3000
V(network_M_Base)$color <- "Black"
vertex_attr(network_M_Base)
V(network_M_Base)$label <- c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18)
plot(network_M_Base, layout= layout.circle, vertex.label.color="white", vertex.label.cex=0.7, vertex.label.font= 2,
    # main= "Biomass flow D.Mawsoni- Base", 
     edge.color="slategray",
     edge.arrow.size = 0.1, vertex.label.family="Helvetica", vertex.label.dist= 0, vertex.label.degree= pi/2, edge.curved=.1)
# legend(x= -1.5, y= 0.7, legend_label, col = "black", cex = 0.6, bty = "n", ncol=1)

#M_KI diff

M_KI <- matrix_KI_ordered
M_KI[,c(1:17)] <- 0
network_M_KI <- graph_from_adjacency_matrix(M_KI, weighted= TRUE, mode= "directed")
V(network_M_KI)$size <- 10
E(network_M_KI)$width <- E(network_M_KI)$weight/3000
V(network_M_KI)$color <- "black"
cols <- c("purple", "orange","orange","orange","orange","orange","orange","orange","orange","orange","orange","orange","orange","orange","orange","orange","orange","orange")
E(network_M_KI)$color <- cols
V(network_M_KI)$label <- c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18)
plot(network_M_KI, layout= layout.circle, vertex.label.color="white",vertex.label.cex=0.6,
     main= "Biomass flow D.Mawsoni- KI",
     edge.arrow.size = 0.1, vertex.label.family="Helvetica", vertex.label.dist= 0, vertex.label.degree= pi/2, edge.curved=.1)
# legend(x=-1.5, y= 0.6, c(V(network_M_KI)$name), col = cols, pch = 18, pt.bg = V(network_M_KD)$label, pt.cex =0.5, cex = 0.6, bty = "n", ncol=1)

#M_KD diff

M_KD <- matrix_KD_ordered
M_KD[,c(1:17)] <- 0

network_M_KD <- graph_from_adjacency_matrix(M_KD, weighted= TRUE, mode= "directed")
V(network_M_KD)$size <- 10
E(network_M_KD)$width <- E(network_M_KD)$weight/3000
V(network_M_KD)$color <- "black"
vertex_attr(network_M_KD)
V(network_M_KD)$label <- c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18)
cols <- c("orange", "purple","orange", "purple", "purple", "purple","purple","purple","purple","purple","purple","purple","purple","purple","purple","purple","purple","purple")
E(network_M_KD)$color <- cols
plot(network_M_KD, layout= layout.circle, vertex.label.color="white",vertex.label.cex=0.6,
     main= "Biomass flow D.Mawsoni- KD", 
     edge.arrow.size = 0.1, vertex.label.family="Helvetica", vertex.label.dist= 0, vertex.label.degree= pi/2, edge.curved=.1)
# legend(x=-1.5, y= 0.6, c(V(network_M_KD)$name), col = cols, pch = 18, pt.bg = V(network_M_KD)$label, pt.cex =0.5, cex = 0.6, bty = "n", ncol=1)

#M_LI DIFF
M_LI <- matrix_LI_ordered
M_LI[,c(1:17)] <- 0

network_M_LI <- graph_from_adjacency_matrix(M_LI, weighted= TRUE, mode= "directed")
V(network_M_LI)$size <- 10
E(network_M_LI)$width <- E(network_M_LI)$weight/3000
V(network_M_LI)$color <- "black"
cols <- c("orange","purple", "purple", "purple", "purple","purple","purple","purple","purple","purple","purple","purple","purple","purple","purple","purple","purple", "purple")
E(network_M_LI)$color <- cols
V(network_M_LI)$label <- c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18)
plot(network_M_LI, layout= layout.circle, vertex.label.color="white",vertex.label.cex=0.6,
     main= "Biomass flow D.Mawsoni- LI",
     edge.arrow.size = 0.1, vertex.label.family="Helvetica", vertex.label.dist= 0, vertex.label.degree= pi/2, edge.curved=.1)
# legend(x=-1.5, y= 0.6, c(V(network_M_LI)$name), col = cols, pch = 18, pt.bg = V(network_M_KD)$label, pt.cex =0.5, cex = 0.6, bty = "n", ncol=1)

#M_LD diff

M_LD <- matrix_LD_ordered
M_LD[,c(1:17)] <- 0
network_M_LD <- graph_from_adjacency_matrix(M_LD, weighted= TRUE, mode= "directed")
V(network_M_LD)$size <- 10
E(network_M_LD)$width <- E(network_M_LD)$weight/3000
V(network_M_LD)$color <- "black"
cols <- c("purple", "orange","orange","orange","orange","orange","orange","orange","orange","orange","orange","orange","orange","orange","orange","orange","orange","orange")
E(network_M_LD)$color <- cols
V(network_M_LD)$label <- c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18)
plot(network_M_LD, layout= layout.circle, vertex.label.color="white",vertex.label.cex=0.6,
     main= "Biomass flow D.Mawsoni- LD",
     edge.arrow.size = 0.1, vertex.label.family="Helvetica", vertex.label.dist= 0, vertex.label.degree= pi/2, edge.curved=.1)
# legend(x=-1.5, y= 0.6, c(V(network_M_LD)$name), col = cols, pch = 18, pt.bg = V(network_M_KD)$label, pt.cex =0.5, cex = 0.6, bty = "n", ncol=1)


#M_KILI_DIFF
M_KILI <- matrix_KILI_ordered
M_KILI[,c(1:17)] <- 0
network_M_KILI <- graph_from_adjacency_matrix(M_KILI, weighted= TRUE, mode= "directed")
V(network_M_KILI)$size <- 10
E(network_M_KILI)$width <- E(network_M_KILI)$weight/3000
cols <- c("purple","purple","purple","purple","purple","purple","purple","purple","purple","purple","purple","orange","orange","orange","orange","orange","orange","orange")
E(network_M_KILI)$color <- cols
V(network_M_KILI)$label <- c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18)
V(network_M_KILI)$color <- "black"
plot(network_M_KILI, layout= layout.circle, vertex.label.color="white",vertex.label.cex=0.6,
     main= "Biomass flow D.Mawsoni- KI_LI",
     edge.arrow.size = 0.1, vertex.label.family="Helvetica", vertex.label.dist= 0, vertex.label.degree= pi/2, edge.curved=.1)
# legend(x=-1.5, y= 0.6, c(V(network_M_KILI)$name), col = cols, pch = 18, pt.bg = V(network_M_KD)$label, pt.cex =0.5, cex = 0.6, bty = "n", ncol=1)

#M_KDLD_DIFF

M_KDLD <- matrix_KDLD_ordered
M_KDLD[,c(1:17)] <- 0
network_M_KDLD <- graph_from_adjacency_matrix(M_KDLD, weighted= TRUE, mode= "directed")
V(network_M_KDLD)$size <- 10
E(network_M_KDLD)$width <- E(network_M_KDLD)$weight/3000
V(network_M_KDLD)$color <- "black"
cols <- c("orange","orange","orange","orange","orange","orange","orange","orange","orange","orange","orange","purple","purple","purple","purple","purple","purple","purple")
E(network_M_KDLD)$color <- cols
V(network_M_KDLD)$label <- c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18)
plot(network_M_KDLD, layout= layout.circle, vertex.label.color="white",vertex.label.cex=0.6,
     main= "Biomass flow D.Mawsoni- KD_LD",
     edge.arrow.size = 0.1, vertex.label.family="Helvetica", vertex.label.dist= 0, vertex.label.degree= pi/2, edge.curved=.1)
# legend(x=-1.5, y= 0.6, c(V(network_M_KDLD)$name), col = cols, pch = 18, pt.bg = V(network_M_KD)$label, pt.cex =0.5, cex = 0.6, bty = "n", ncol=1)


#M_KILD_DIFF
M_KILD <- matrix_KILD_ordered
M_KILD[,c(1:17)] <- 0
network_M_KILD <- graph_from_adjacency_matrix(M_KILD, weighted= TRUE, mode= "directed")
V(network_M_KILD)$size <- 10
E(network_M_KILD)$width <- E(network_M_KILD)$weight/3000
V(network_M_KILD)$color <- "black"
cols <- c("purple", "orange","orange","orange","orange","orange","orange","orange","orange","orange","orange","orange","orange","orange","orange","orange","orange","orange")
E(network_M_KILD)$color <- cols
V(network_M_KILD)$label <- c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18)
plot(network_M_KILD, layout= layout.circle, vertex.label.color="white",vertex.label.cex=0.6,
     main= "Biomass flow D.mawsoni KILD",
     edge.arrow.size = 0.1, vertex.label.family="Helvetica", vertex.label.dist= 0, vertex.label.degree= pi/2, edge.curved=.1)
# legend(x=-1.5, y= 0.6, c(V(network_M_KILD)$name), col = cols, pch = 18, pt.bg = V(network_M_KD)$label, pt.cex =0.5, cex = 0.6, bty = "n", ncol=1)


#matrix_KDLI

M_KDLI <- matrix_KDLI_ordered
M_KDLI[,c(1:17)] <- 0
network_M_KDLI <- graph_from_adjacency_matrix(M_KDLI, weighted= TRUE, mode= "directed")
V(network_M_KDLI)$size <- 10
E(network_M_KDLI)$width <- E(network_M_KDLI)$weight/3000
V(network_M_KDLI)$color <- "black"
cols <- c("orange","purple", "purple", "purple", "purple","purple","purple","purple","purple","purple","purple","purple","purple","purple","purple","purple","purple", "purple")
E(network_M_KDLI)$color <- cols
V(network_M_KDLI)$label <- c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18)
plot(network_M_KDLI, layout= layout.circle, vertex.label.color="white",vertex.label.cex=0.6,
     main= "Biomass flow D.mawsoni KDLI",
     edge.arrow.size = 0.1, vertex.label.family="Helvetica", vertex.label.dist= 0, vertex.label.degree= pi/2, edge.curved=.1)
# legend(x=-1.5, y= 1, c(V(network_M_KDLI)$name), col = cols, pch = 18, pt.bg = V(network_M_KDLI)$label, pt.cex =0.5, cex = 0.6, bty = "n", ncol=1)

```

Playing with network structure

```{r}
#bring in fish icon

library(png)

image <- readPNG("Patagonian.png")


```

