---
title: "Network_plots"
output: html_document
---
```{r}
library(tidyr)

```

DIET MATRICES FIRST

get data
```{r}
library(data.table)

# kappa (base, +5%, -5%) Lambda (base, +1/2%, -1/2%)
kappa_2 <- c(0.256,0.2688,0.243)
lambda_2 <- c(2.05,2.06,2.040)

# kappa (base, +5%, -5%) Lambda (base, +5%, -5%)
# kappa_5 <- c(0.256,0.2688,0.243)
# lambda_5 <- c(2.05,2.153,1.948)

# grid <- expand.grid(kappa = kappa_2, lambda= lambda_2)
grid <- expand.grid(kappa = kappa_2, lambda= lambda_2)


grid$name <- c("Base", "KI", "KD", "LI", "KI_LI", "KD_LI", "LD", "KI_LD", "KD_LD") 

df_diet <- read.csv("df_diet_d.csv")
df_diet$name <- as.factor(df_diet$name)
grid$name <- as.factor(grid$name)
df_diet2 <- left_join(df_diet, grid)
```


Base Model
```{r}
Base <- filter(df_diet2, name== "Base")
colnames(Base) <- c("name", "Predator", "size", "Prey", "biomass","kappa","lambda")
#summarise by biomass
df_summary_Base <- Base %>% 
  group_by(Predator, Prey) %>% 
  summarise(totalbiomass = sum(biomass))
#convert data frame to matrix
##matrix_biomass_prey <- pivot_wider(df_summary, names_from = Prey, values_from = totalbiomass)
matrix_biomass_Base <- pivot_wider(df_summary_Base, names_from = Predator, values_from = totalbiomass)
#check format is in matrix form?
##Tmatrix_biomass_prey <- as.matrix(matrix_biomass_prey)
Tmatrix_biomass_Base <- as.matrix(matrix_biomass_Base)
#rename column with predator names
rownames(Tmatrix_biomass_Base) <- Tmatrix_biomass_Base[,1]
#remove column
matrix_edit_Base <- Tmatrix_biomass_Base[,-1]
#First add resource to column: (make square)
resource_matrix_Base <- cbind(matrix_edit_Base, c(0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0))
colnames(resource_matrix_Base) <- SOparams[,1]

#need to convert character matrix to numeric matrix to divide.


# FOR RELATIVE VALUES
# convert to numeric for dividing later!
resource_matrix_Base_v2 <- matrix(as.numeric(resource_matrix_Base), ncol= ncol(resource_matrix_Base))
# matrix_Base_relative <- matrix(as.numeric((resource_matrix_Base_v2/resource_matrix_Base_v2)), ncol=ncol(resource_matrix_Base_v2)) #converting to numeric vector then back to matrix
matrix_Base_relative <- resource_matrix_Base_v2/resource_matrix_Base_v2
matrix_Base_relative[is.nan(matrix_Base_relative)] = 0 #remove nans, make 0s
names <- c("B.antarcticus", "C.gunnari", "C.microdon","C.piriei","D.eleginoides","D.mawsoni","E.antarctica","E.carlsbergi","G.braueri","G.fraseri","G.nicholsi","K.anderssoni", "N.achirus","N.coatsi","P.antarcticum","P.bolini","P.gracilis", "Resource")
rownames(matrix_Base_relative) <- names
colnames(matrix_Base_relative) <- names
#order by species
SOparams <- read.csv("SOparams.csv")
#order params file
SOparams_r <- SOparams[order(SOparams$w_inf),]
rownames(SOparams_r) <- SOparams_r[,1]
SOparams_r <- SOparams_r[,-1]
#then order matrix
#columns re-ordered
matrix_Base_ordered <- select(as.data.frame(matrix_Base_relative),SOparams_r$species)
matrix_Base_ordered <- as.matrix(select(as.data.frame(t(matrix_Base_ordered)),SOparams_r$species))
#transpose back
matrix_Base_ordered <- t(matrix_Base_ordered)


```

KI
```{r}
# KI <- readRDS("KI.Rdata")
KI <- filter(df_diet2, name== "KI")
# dim(df_test_Base)
colnames(KI) <- c("name", "Predator", "size", "Prey", "biomass","kappa","lambda")
#summarise by biomass
df_summary_KI <- KI %>% 
  group_by(Predator, Prey) %>% 
  summarise(totalbiomass = sum(biomass))
#convert data frame to matrix
##matrix_biomass_prey <- pivot_wider(df_summary, names_from = Prey, values_from = totalbiomass)
matrix_biomass_KI<- pivot_wider(df_summary_KI, names_from = Predator, values_from = totalbiomass)
Tmatrix_biomass_KI <- as.matrix(matrix_biomass_KI)
#rename column with predator names
rownames(Tmatrix_biomass_KI) <- Tmatrix_biomass_KI[,1]
#remove column
matrix_edit_KI <- Tmatrix_biomass_KI[,-1] 
#First add resource to column: (make square)
resource_matrix_KI <- cbind(matrix_edit_KI, c(0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0))
colnames(resource_matrix_KI) <- SOparams[,1]


# order matrix
matrix_KI_ordered <- select(as.data.frame(resource_matrix_KI),SOparams_r$species)
matrix_KI_ordered <- as.matrix(select(as.data.frame(t(matrix_KI_ordered)),SOparams_r$species))
#transpose back
matrix_KI_ordered <- t(matrix_KI_ordered)

#FOR RELATIVE
#convert to numeric for dividing later!
resource_matrix_KI_v2 <- matrix(as.numeric(resource_matrix_KI), ncol= ncol(resource_matrix_KI))
#need to convert character matrix to numeric matrix to divide.
matrix_KI_relative <- ((resource_matrix_KI_v2/resource_matrix_Base_v2)) #converting to numeric vector then back to matrix
matrix_KI_relative[is.nan(matrix_KI_relative)] = 0 #remove nans, make 0s
names <- c("B.antarcticus", "C.gunnari", "C.microdon","C.piriei","D.eleginoides","D.mawsoni","E.antarctica","E.carlsbergi","G.braueri","G.fraseri","G.nicholsi","K.anderssoni", "N.achirus","N.coatsi","P.antarcticum","P.bolini","P.gracilis", "Resource")
rownames(matrix_KI_relative) <- names
colnames(matrix_KI_relative) <- names


```

KD
```{r}

# KD <- readRDS("KD.Rdata")
KD <- filter(df_diet2, name== "KD")
colnames(KD) <- c("name", "Predator", "size", "Prey", "biomass","kappa","lambda")
#summarise by biomass
df_summary_KD <- KD %>% 
  group_by(Predator, Prey) %>% 
  summarise(totalbiomass = sum(biomass))
#convert data frame to matrix
##matrix_biomass_prey <- pivot_wider(df_summary, names_from = Prey, values_from = totalbiomass)
matrix_biomass_KD <- pivot_wider(df_summary_KD, names_from = Predator, values_from = totalbiomass)
#check format is in matrix form?
##Tmatrix_biomass_prey <- as.matrix(matrix_biomass_prey)
Tmatrix_biomass_KD <- as.matrix(matrix_biomass_KD)
#rename column with predator names
rownames(Tmatrix_biomass_KD) <- Tmatrix_biomass_KD[,1]
#remove column
matrix_edit_KD <- Tmatrix_biomass_KD[,-1] 
#add resource to make square
resource_matrix_KD <- cbind(matrix_edit_KD, c(0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0))
colnames(resource_matrix_KD) <- SOparams[,1]


#order by species
#columns re-ordered
matrix_KD_ordered <- select(as.data.frame(resource_matrix_KD),SOparams_r$species)
matrix_KD_ordered <- as.matrix(select(as.data.frame(t(matrix_KD_ordered)),SOparams_r$species))
#transpose back
matrix_KD_ordered <- t(matrix_KD_ordered)


#FOR RELATIVE
#make numeric and find relative value
# convert to numeric for dividing later!
resource_matrix_KD_v2 <- matrix(as.numeric(resource_matrix_KD), ncol= ncol(resource_matrix_KD))
matrix_KD_relative <- ((resource_matrix_KD_v2/resource_matrix_Base_v2)) #converting to numeric vector then back to matrix
matrix_KD_relative[is.nan(matrix_KD_relative)] = 0 #remove nans, make 0s
names <- c("B.antarcticus", "C.gunnari", "C.microdon","C.piriei","D.eleginoides","D.mawsoni","E.antarctica","E.carlsbergi","G.braueri","G.fraseri","G.nicholsi","K.anderssoni", "N.achirus","N.coatsi","P.antarcticum","P.bolini","P.gracilis", "Resource")
rownames(matrix_KD_relative) <- names
colnames(matrix_KD_relative) <- names



```

LI
```{r}

```


LD

```{r}

```


KI_LI
```{r}

# KI_LI <- readRDS("KI_LI.Rdata")
KI_LI <- filter(df_diet2, name== "KI_LI")

colnames(KI_LI) <- c("name", "Predator", "size", "Prey", "biomass","kappa","lambda")
#summarise by biomass
df_summary_KILI <- KI_LI %>% 
  group_by(Predator, Prey) %>% 
  summarise(totalbiomass = sum(biomass))
#convert data frame to matrix
##matrix_biomass_prey <- pivot_wider(df_summary, names_from = Prey, values_from = totalbiomass)
matrix_biomass_KILI <- pivot_wider(df_summary_KILI, names_from = Predator, values_from = totalbiomass)
#check format is in matrix form?
##Tmatrix_biomass_prey <- as.matrix(matrix_biomass_prey)
Tmatrix_biomass_KILI <- as.matrix(matrix_biomass_KILI)
#rename column with predator names
rownames(Tmatrix_biomass_KILI) <- Tmatrix_biomass_KILI[,1]
#remove column
matrix_edit_KILI <- Tmatrix_biomass_KILI[,-1] 
#add resource to make square
resource_matrix_KILI <- cbind(matrix_edit_KILI, c(0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0))
colnames(resource_matrix_KILI) <- SOparams[,1]

matrix_KILI_ordered <- select(as.data.frame(resource_matrix_KILI),SOparams_r$species)
matrix_KILI_ordered <- as.matrix(select(as.data.frame(t(matrix_KILI_ordered)),SOparams_r$species))
#transpose back
matrix_KILI_ordered <- t(matrix_KILI_ordered)

# #FOR RELATIVE VALUE
# #convert to numeric for dividing
resource_matrix_KILI_v2 <- matrix(as.numeric(resource_matrix_KILI), ncol= ncol(resource_matrix_KILI))
# #make numeric
matrix_KILI_relative <- ((resource_matrix_KILI_v2/resource_matrix_Base_v2)) #converting to numeric vector then back to matrix
matrix_KILI_relative[is.nan(matrix_KILI_relative)] = 0 #remove nans, make 0s
names <- c("B.antarcticus", "C.gunnari", "C.microdon","C.piriei","D.eleginoides","D.mawsoni","E.antarctica","E.carlsbergi","G.braueri","G.fraseri","G.nicholsi","K.anderssoni", "N.achirus","N.coatsi","P.antarcticum","P.bolini","P.gracilis", "Resource")
rownames(matrix_KILI_relative) <- names
colnames(matrix_KILI_relative) <- names


```

KD_LD
```{r}

```

Plot them all!

```{r}
#plot network using matrix
#matrix Base
library(igraph)
network_Base <- graph_from_adjacency_matrix(matrix_Base_relative, weighted= TRUE, mode= "directed")
V(network_Base)$size <- log(SOparams_r$w_inf)*3
E(network_Base)$width <- E(network_Base)$weight
colfunc <- colorRampPalette(c("gray80", "darkred"))
cols<-colfunc(18)
V(network_Base)$color <- cols
vertex_attr(network_Base)
V(network_Base)$label <- c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18)
#to change the edge colours: can do by colouring from the source 
edge.start <- ends(network_Base, es=E(network_Base), names=F)[,1]
edge.col <- V(network_Base)$color[edge.start]
plot(network_Base, layout= layout.circle, vertex.label.color="black",vertex.label.cex=0.6,
     main= "Biomass flow Base", edge.color=edge.col,
     edge.arrow.size = 0.1, vertex.label.family="Helvetica", vertex.label.dist= 0, vertex.label.degree= pi/2, edge.curved=.1)
legend(x=1.5, y= 0.4, c(V(network_Base)$name), col = cols, pch = 18, pt.bg = V(network_Base)$label, pt.cex =0.5, cex = 0.6, bty = "n", ncol=2)

#matrix KI
library(igraph)
network_KI <- graph_from_adjacency_matrix(matrix_KI_relative, weighted= TRUE, mode= "directed")
V(network_KI)$size <- log(SOparams_r$w_inf)*3
E(network_KI)$width <- (E(network_KI)$weight)
colfunc <- colorRampPalette(c("gray80", "darkred"))
cols<-colfunc(18)
V(network_KI)$color <- cols
vertex_attr(network_KI)
V(network_KI)$label <- c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18)
#to change the edge colours: can do by colouring from the source 
edge.start <- ends(network_KI, es=E(network_KI), names=F)[,1]
edge.col <- V(network_KI)$color[edge.start]
plot(network_KI, layout= layout.circle, vertex.label.color="black",vertex.label.cex=0.6,
     main= "Biomass flow KI", edge.color=edge.col,
     edge.arrow.size = 0.1, vertex.label.family="Helvetica", vertex.label.dist= 0, vertex.label.degree= pi/2, edge.curved=.1)
legend(x=1.5, y= 0.4, c(V(network_KI)$name), col = cols, pch = 18, pt.bg = V(network_KI)$label, pt.cex =0.5, cex = 0.6, bty = "n", ncol=2)

#matrix KD
library(igraph)
network_KD <- graph_from_adjacency_matrix(matrix_KD_relative, weighted= TRUE, mode= "directed")
V(network_KD)$size <- log(SOparams_r$w_inf)*3
E(network_KD)$width <- E(network_KD)$weight
colfunc <- colorRampPalette(c("gray80", "darkred"))
cols<-colfunc(18)
V(network_KD)$color <- cols
vertex_attr(network_KD)
V(network_KD)$label <- c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18)
#to change the edge colours: can do by colouring from the source 
edge.start <- ends(network_KD, es=E(network_KD), names=F)[,1]
edge.col <- V(network_KD)$color[edge.start]
plot(network_KD, layout= layout.circle, vertex.label.color="black", vertex.label.cex=0.6,
     main= "Biomass flow KD", edge.color= edge.col,
     edge.arrow.size = 0.1, vertex.label.family="Helvetica", vertex.label.dist= 0, vertex.label.degree= pi/2, edge.curved=.1)
legend(x=1.5, y= 0.4, c(V(network_KI)$name), col = cols, pch = 18, pt.bg = V(network_KI)$label, pt.cex =0.5, cex = 0.6, bty = "n", ncol=2)

#matrix KI_LI

library(igraph)
network_KILI <- graph_from_adjacency_matrix(matrix_KILI_relative, weighted= TRUE, mode= "directed")
V(network_KILI)$size <- log(SOparams_r$w_inf)*3
E(network_KILI)$width <- E(network_KILI)$weight
colfunc <- colorRampPalette(c("gray80", "darkred"))
cols<-colfunc(18)
V(network_KILI)$color <- cols
vertex_attr(network_KILI)
V(network_KILI)$label <- c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18)
#to change the edge colours: can do by colouring from the source 
edge.start <- ends(network_KILI, es=E(network_KILI), names=F)[,1]
edge.col <- V(network_KILI)$color[edge.start]
plot(network_KILI, layout= layout.circle, vertex.label.color="black",vertex.label.cex=0.6,
     main= "Biomass flow KILI", edge.color=edge.col,
     edge.arrow.size = 0.1, vertex.label.family="Helvetica", vertex.label.dist= 0, vertex.label.degree= pi/2, edge.curved=.1)
legend(x=1.5, y= 0.4, c(V(network_KILI)$name), col = cols, pch = 18, pt.bg = V(network_KILI)$label, pt.cex =0.5, cex = 0.6, bty = "n", ncol=2)
```



